[[pages]]
name = "Introduction"
path = "main.py"

[[pages]]
name = "Extract Accuracy with reps"
path = "extractAccuracyRep.py"

[[pages]]
name = "Extract model stability"
path = "modelStability.py"

[[pages]]
name = "Extract ROC"
path = "extractROC.py"


[[pages]]
name = "Credits"
path = "credits.py"
